package main

import (
	"fmt"
	"os"
	"path/filepath"
	"slices"
	"sort"
	"strings"

	"cmdcards/internal/content"
	"cmdcards/internal/engine"
)

func runExportWiki(lib *content.Library, args []string) error {
	outPath := filepath.Join("docs", "CONTENT_WIKI.md")
	if len(args) > 0 && strings.TrimSpace(args[0]) != "" {
		outPath = args[0]
	}
	body := buildContentWiki(lib)
	if err := os.MkdirAll(filepath.Dir(outPath), 0o755); err != nil {
		return err
	}
	if err := os.WriteFile(outPath, []byte(body), 0o644); err != nil {
		return err
	}
	fmt.Println("wiki exported to", outPath)
	return nil
}

func buildContentWiki(lib *content.Library) string {
	var b strings.Builder
	b.WriteString("# RuneShell Content Wiki\n\n")
	b.WriteString("This file is generated by `go run ./cmd/cmdcards export-wiki`.\n")
	b.WriteString("It should be regenerated whenever content changes.\n\n")
	b.WriteString("## Overview\n\n")
	b.WriteString(fmt.Sprintf("- Classes: %d\n- Cards: %d\n- Relics: %d\n- Potions: %d\n- Equipments: %d\n- Encounters: %d\n- Events: %d\n\n",
		len(lib.Classes), len(lib.Cards), len(lib.Relics), len(lib.Potions), len(lib.Equipments), len(lib.Encounters), len(lib.Events)))
	b.WriteString("## Keyword Dictionary\n\n")
	for _, line := range wikiKeywordLines() {
		b.WriteString("- " + line + "\n")
	}
	b.WriteString("\n## Classes\n\n")
	for _, class := range lib.ClassList() {
		b.WriteString("### " + class.Name + " (`" + class.ID + "`)\n\n")
		b.WriteString(class.Description + "\n\n")
		b.WriteString(fmt.Sprintf("- HP: %d\n- Energy: %d\n- Starting deck: %s\n- Starting relics: %s\n- Starting potions: %s\n- Starting equipment: %s\n\n",
			class.BaseHP, class.MaxEnergy, strings.Join(class.StartingDeck, ", "), strings.Join(class.StartingRelics, ", "), strings.Join(class.StartingPotions, ", "), strings.Join(class.StartingEquipment, ", ")))
	}
	b.WriteString("## Cards\n\n")
	for _, class := range append(lib.ClassList(), content.ClassDef{ID: "neutral", Name: "Neutral"}) {
		var cards []content.CardDef
		for _, card := range lib.CardList() {
			if card.ClassID == class.ID {
				cards = append(cards, card)
			}
		}
		if len(cards) == 0 {
			continue
		}
		b.WriteString("### " + class.Name + "\n\n")
		for _, card := range cards {
			b.WriteString("#### " + card.Name + " (`" + card.ID + "`)\n\n")
			b.WriteString(fmt.Sprintf("- Cost: %d\n- Rarity: %s\n- Tags: %s\n", card.Cost, card.Rarity, strings.Join(card.Tags, ", ")))
			if len(card.Flags) > 0 {
				b.WriteString("- Flags: " + strings.Join(card.Flags, ", ") + "\n")
			}
			b.WriteString("- Base: " + engine.DescribeEffects(lib, card.Effects) + "\n")
			if len(card.UpgradeEffects) > 0 {
				b.WriteString("- Upgrade: " + engine.DescribeEffects(lib, card.UpgradeEffects) + "\n")
			}
			if strings.TrimSpace(card.Description) != "" {
				b.WriteString("- Description: " + card.Description + "\n")
			}
			b.WriteString("\n")
		}
	}
	b.WriteString("## Relics\n\n")
	for _, relic := range lib.RelicList() {
		b.WriteString("### " + relic.Name + " (`" + relic.ID + "`)\n\n")
		b.WriteString("- Rarity: " + relic.Rarity + "\n")
		if len(relic.Flags) > 0 {
			b.WriteString("- Flags: " + strings.Join(relic.Flags, ", ") + "\n")
		}
		b.WriteString("- Effects: " + engine.DescribeEffects(lib, relic.Effects) + "\n")
		b.WriteString("- Description: " + relic.Description + "\n\n")
	}
	b.WriteString("## Equipments\n\n")
	for _, equipment := range lib.EquipmentList() {
		b.WriteString("### " + equipment.Name + " (`" + equipment.ID + "`)\n\n")
		b.WriteString(fmt.Sprintf("- Slot: %s\n- Rarity: %s\n- Effects: %s\n- Description: %s\n\n",
			equipment.Slot, equipment.Rarity, engine.DescribeEffects(lib, equipment.Effects), equipment.Description))
	}
	b.WriteString("## Potions\n\n")
	for _, potion := range lib.PotionList() {
		b.WriteString("### " + potion.Name + " (`" + potion.ID + "`)\n\n")
		b.WriteString(fmt.Sprintf("- Rarity: %s\n- Effects: %s\n- Description: %s\n\n",
			potion.Rarity, engine.DescribeEffects(lib, potion.Effects), potion.Description))
	}
	b.WriteString("## Workshop Services\n\n")
	for _, class := range lib.ClassList() {
		run, err := engine.NewRun(lib, engine.DefaultProfile(lib), engine.ModeStory, class.ID, 1)
		if err != nil {
			continue
		}
		shop := engine.StartShop(lib, run)
		services := make([]engine.ShopOffer, 0, len(shop.Offers))
		for _, offer := range shop.Offers {
			if offer.Kind == "service" {
				services = append(services, offer)
			}
		}
		if len(services) == 0 {
			continue
		}
		b.WriteString("### " + class.Name + "\n\n")
		for _, service := range services {
			b.WriteString(fmt.Sprintf("- %s (`%s`): %s | Price %d\n", service.Name, service.ItemID, service.Description, service.Price))
		}
		b.WriteString("\n")
	}
	b.WriteString("## Encounters\n\n")
	for _, encounter := range sortedEncounters(lib) {
		b.WriteString("### " + encounter.Name + " (`" + encounter.ID + "`)\n\n")
		b.WriteString(fmt.Sprintf("- Kind: %s\n- Act: %d\n- HP: %d\n- Gold reward: %d\n- Card reward count: %d\n",
			encounter.Kind, encounter.Act, encounter.HP, encounter.GoldReward, encounter.CardReward))
		if len(encounter.Passives) > 0 {
			b.WriteString("- Passives: " + engine.DescribeEffects(lib, encounter.Passives) + "\n")
		}
		b.WriteString("- Intent cycle:\n")
		for _, intent := range encounter.IntentCycle {
			b.WriteString(fmt.Sprintf("  - %s: %s | %s\n", intent.Name, intent.Description, engine.DescribeEffects(lib, intent.Effects)))
		}
		b.WriteString("\n")
	}
	b.WriteString("## Events\n\n")
	for _, event := range sortedEvents(lib) {
		b.WriteString("### " + event.Name + " (`" + event.ID + "`)\n\n")
		b.WriteString("- Acts: " + intsToList(event.Acts) + "\n")
		if len(event.Flags) > 0 {
			b.WriteString("- Flags: " + strings.Join(event.Flags, ", ") + "\n")
		}
		b.WriteString("- Description: " + event.Description + "\n")
		b.WriteString("- Choices:\n")
		for _, choice := range event.Choices {
			b.WriteString(fmt.Sprintf("  - %s (`%s`): %s | %s\n", choice.Label, choice.ID, choice.Description, engine.DescribeEffects(lib, choice.Effects)))
		}
		b.WriteString("\n")
	}
	b.WriteString("## Effect Ops In Use\n\n")
	for _, line := range wikiEffectLines(lib) {
		b.WriteString("- " + line + "\n")
	}
	return b.String()
}

func wikiKeywordLines() []string {
	return []string{
		"attack / skill / spell: card type tags used for build synergies and UI coloring.",
		"strength / weak / vulnerable / frail / burn / poison / guard / focus / regen / taunt / sheltered: common combat statuses.",
		"run / combat / turn: augment scopes for persistent, next-combat, or next-turn card modifications.",
		"status_card / unplayable / end_turn_trigger / purge_on_discard: flags used by enemy-generated temporary debuff cards.",
		"choose / all / choose_upgradable / all_upgradable: augment selectors.",
		"coop_only: content that only appears in co-op capable runs or multiplayer flows.",
		"weapon / armor / accessory: the three equipment slots.",
	}
}

func wikiEffectLines(lib *content.Library) []string {
	seen := map[string]string{}
	var add func(effect content.Effect)
	add = func(effect content.Effect) {
		if effect.Op == "" {
			return
		}
		if _, ok := seen[effect.Op]; !ok {
			seen[effect.Op] = engine.DescribeEffect(lib, effect)
		}
		for _, nested := range effect.Effects {
			add(nested)
		}
	}
	for _, card := range lib.CardList() {
		for _, effect := range card.Effects {
			add(effect)
		}
		for _, effect := range card.UpgradeEffects {
			add(effect)
		}
	}
	for _, relic := range lib.RelicList() {
		for _, effect := range relic.Effects {
			add(effect)
		}
	}
	for _, potion := range lib.PotionList() {
		for _, effect := range potion.Effects {
			add(effect)
		}
	}
	for _, equipment := range lib.EquipmentList() {
		for _, effect := range equipment.Effects {
			add(effect)
		}
	}
	for _, encounter := range sortedEncounters(lib) {
		for _, effect := range encounter.Passives {
			add(effect)
		}
		for _, intent := range encounter.IntentCycle {
			for _, effect := range intent.Effects {
				add(effect)
			}
		}
	}
	for _, event := range sortedEvents(lib) {
		for _, choice := range event.Choices {
			for _, effect := range choice.Effects {
				add(effect)
			}
		}
	}
	keys := make([]string, 0, len(seen))
	for key := range seen {
		keys = append(keys, key)
	}
	sort.Strings(keys)
	lines := make([]string, 0, len(keys))
	for _, key := range keys {
		lines = append(lines, fmt.Sprintf("`%s`: %s", key, seen[key]))
	}
	return lines
}

func sortedEncounters(lib *content.Library) []content.EncounterDef {
	out := make([]content.EncounterDef, 0, len(lib.Encounters))
	for _, encounter := range lib.Encounters {
		out = append(out, encounter)
	}
	sort.Slice(out, func(i, j int) bool {
		if out[i].Act != out[j].Act {
			return out[i].Act < out[j].Act
		}
		if out[i].Kind != out[j].Kind {
			return out[i].Kind < out[j].Kind
		}
		return out[i].Name < out[j].Name
	})
	return out
}

func sortedEvents(lib *content.Library) []content.EventDef {
	out := make([]content.EventDef, 0, len(lib.Events))
	for _, event := range lib.Events {
		out = append(out, event)
	}
	sort.Slice(out, func(i, j int) bool {
		left := slices.Min(out[i].Acts)
		right := slices.Min(out[j].Acts)
		if left != right {
			return left < right
		}
		return out[i].Name < out[j].Name
	})
	return out
}

func intsToList(values []int) string {
	parts := make([]string, 0, len(values))
	for _, value := range values {
		parts = append(parts, fmt.Sprintf("%d", value))
	}
	return strings.Join(parts, ", ")
}
